[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[terminal]
shell = "/usr/bin/zsh"

[font]
normal = { family = "MesloLGMDZ Nerd Font" }
bold = { family = "MesloLGMDZ Nerd Font" }
italic = { family = "MesloLGMDZ Nerd Font" }
bold_italic = { family = "MesloLGMDZ Nerd Font" }
size = 12
offset = { x = -1 }
